language: scala
jdk:
  - openjdk6
scala:
  - 2.11.7

before_install:
  - export PATH=$PWD/bin:$PATH

install:
  - sudo add-apt-repository -y ppa:cassou/emacs &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq emacs24 emacs24-el aspell

script:
  # only testing emacs starts up ok for now
  - emacs -batch --no-init-file --load .emacs-test.el --load .emacs.d/init.el --eval '(kill-emacs 0)'
